server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 指定环境，决定选择配置文件
  profiles:
    active: local
  application:
    name: user-manage-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qweasd!@#QWE
    url: jdbc:mysql://localhost:3306/db_multi?characterEncoding=UTF8&useUnicode=true&useSSL=false
  mail:
    protocol: smtp #邮件协议
    host: smtp.126.com #网易邮箱smtp服务器地址
    port: 25 #默认端口
    username: peng_yujun53@126.com #发件人邮箱地址
    password: WFZHmBrQUXY64pcc #授权码
    default-encoding: UTF-8 #编码字符集

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志打印

# 配置springdoc-openapi，用于文档化和访问API
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha  # 按字母顺序排序操作
  # 配置API文档的访问路径
  api-docs:
    path: /v3/api-docs  # API文档的访问路径
  # 配置API分组，用于组织和管理API
  group-configs:
    - group: 'default'   # API分组名称
      paths-to-match: '/**'  # 匹配所有路径
      packages-to-scan: com.example.mps.controller  # 扫描的包，用于自动发现API

# knife4j的增强配置，不需要增强可以不配（详细版见下小节）
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

sdk:
  client:
    access-key:
    secret-key:

# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo # 通信协议
    port: 22221 # dubbo协议端口
  registry:
    address: nacos://localhost:8848


