server:
  port: 8082

spring:
  application:
    name: multi-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, multi-gateway
      routes:
        - id: api_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
#        - id: add_request_header_route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=yujun, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: multi-fallback
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/fallback

# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: 22223
  registry:
    address: nacos://localhost:8848
